# <center> NUMERICAL ANALYSIS

## <span style='color:blue'> Theme 3 - Numerical Solutions of Eigenvalue Problem (Power Method)

#### <span style='color:red'> [3.1] Power Method with a shift of q

<img src="pics/pmq.png" alt="Drawing" style="width: 600px;margin-center: auto; margin-center: 0;"/>

In [9]:
import numpy as np
import operator

def power(A,x0,q,TOL,N):
    I = np.identity(len(A))
    k = 1                                                         #Step 1
    x_p = np.linalg.norm(x0, np.inf)
    p = 0
    for i in range(0,N):                                          #Step 2
        if(x_p == abs(x0[i])):
            p = i
            break
        
    x = x0/x_p                                                    #Step 3
    
    while(k <= N):                                                #Step 4
        print("-----ITERATION-----", k)
        
        lin_sys = (A - q*I)                                       #Step 5
        if q == 0:
            new_sys = A
        else: 
            if np.linalg.det(lin_sys) != 0:                        
                new_sys = np.linalg.inv(lin_sys)
            else:
                raise ValueError("Sol not Unique. Eigenvalue = ", q2)
        
        y = np.matmul(new_sys,x) # solve linear system
        mu = y[p]                                                 #Step 6 
        print("mu",mu)
        
        y_p = np.linalg.norm(y, np.inf)                           #Step 7
        if y_p == 0:
            raise ValueError("A has eigenval 0, choose new x0")
        p = 0
        for j in range(0,N):
            if( y_p == abs(y[j]) ):
                p = j
                break
        
        ERR = np.linalg.norm((x-(y/y_p)), np.inf)                 #Step 9
        x = y/y[p]
        print("x = \n",x)
        
        if(ERR < TOL):                                            #Step 10
            lam = (1/mu) + q
            print("Procedure was succesful")
            return (lam, x)
        
        k += 1                                                    #Step 11
    print("The maximum number of iterations exceeded")

In [10]:
a = np.array([[2,1,1], [1,2,1], [1,1,2]])
x = np.array([[1],[1],[2]])
TOL = 10**-4
N = 3
q = 0
power(a,x,q,TOL,N)

-----ITERATION----- 1
mu [3.]
x = 
 [[0.83333333]
 [0.83333333]
 [1.        ]]
-----ITERATION----- 2
mu [3.66666667]
x = 
 [[0.95454545]
 [0.95454545]
 [1.        ]]
-----ITERATION----- 3
mu [3.90909091]
x = 
 [[0.98837209]
 [0.98837209]
 [1.        ]]
The maximum number of iterations exceeded


#### <span style='color:red'> [3.2] Inverse Power Method

<img src="pics/ipm.png" alt="Drawing" style="width: 400px;margin-center: auto; margin-center: 0;"/>

In [14]:
def ipower(A,x0,q,TOL,N):
    q1 = np.dot(np.dot(np.matrix.transpose(x0),A1),x0)            #Step 1
    q2 = q1/np.dot(np.matrix.transpose(x0),x0)
    I = np.identity(len(A))
    k = 1                                                         #Step 2
    x_p = np.linalg.norm(x0, np.inf)
    p = 0
    
    for i in range(0,N):                                          #Step 3
        if( x_p == abs(x0[i]) ):
            p = i
            break
        
    x = x0/x_p                                                    #Step 4
    
    while(k <= N):                                                #Step 5
        print("-----ITERATION-----", k)
        
        lin_sys = (A - q*I)                                       #Step 6
        
        if np.linalg.det(lin_sys) != 0:                           #Step 7
            new_sys = np.linalg.inv(lin_sys)
        else:
            raise ValueError("Sol not Unique. Eigenvalue = ", q2)
        y = np.matmul(new_sys,x) # solve linear system
        
        mu = y[p]                                                 #Step 8
        print("mu",mu)
        
        y_p = np.linalg.norm(y, np.inf)                           #Step 9
        p = 0
        for j in range(0,N):
            if( y_p == abs(y[j]) ):
                p = j
                break
        
        ERR = np.linalg.norm(( x-(y/y_p) ), np.inf)               #Step 10
        x = y/y[p]
        print("x = \n",x)
        
        if(ERR < TOL):                                            #Step 11
            lam = (1/mu) + q
            print("Procedure was succesful")
            return (lam, x)
        
        k += 1                                                    #Step 12
    print("The maximum number of iterations exceeded")

In [15]:
A1 = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
x0 = np.array([[1],[-1],[2]])
q = 2 #initial shift
N = 3
Tol = 10**-4
ipower(A1,x0,q,Tol,N)

-----ITERATION----- 1
mu [-0.5]
x = 
 [[ 0. ]
 [ 1. ]
 [-0.5]]
-----ITERATION----- 2
mu [-0.75]
x = 
 [[-0.33333333]
 [ 1.        ]
 [-1.        ]]
-----ITERATION----- 3
mu [-1.16666667]
x = 
 [[-0.14285714]
 [ 1.        ]
 [-0.71428571]]
The maximum number of iterations exceeded
